const { coordinates } = require("@maptiler/client");

module.exports.biblioCba = [
    {
        nombre: 'Biblioteca Popular Almafuerte y CAJU',
        localidad: 'Almafuerte',
        direccion: 'Av.Buenos Aires 263',
        registroConabip: 527,
        geometry: {
            type: "Point",
            coordinates: [
                -64.2554406,
                -32.1968789
            ]
        },
        redes: [{
            nombre: 'Instagram',
            checked: true ,
            link: 'https://www.instagram.com/bpacajudeportes/'
        }]
    },
    {
        nombre: 'Biblioteca Popular Ramón J. Cárcano',
        localidad: 'Bell Ville',
        direccion: 'Córdoba y Sarmiento',
        registroConabip: 528,
        geometry: {
            type: "Point",
            coordinates: [
                -62.6911271,
                -32.6296541
            ]
        },
    },
    {
        nombre: 'Biblioteca Popular Velez Sarsfield',
        localidad: 'Córdoba',
        direccion: 'Lima 995',
        registroConabip: 534,
    },
    {
        nombre: 'Biblioteca Popular Jorge Newbery',
        localidad: 'Cruz del Eje',
        direccion: 'San Martín 147',
        registroConabip: 539,
    },
    {
        nombre: 'Biblioteca Popular D. F. Sarmiento',
        localidad: 'Etruria',
        direccion: 'Bv.Sarmiento 257',
        registroConabip: 543,
    },
    {
        nombre: 'BIBLIOTECA POPULAR FLORENTINO AMEGHINO',
        localidad: 'General Levalle',
        direccion: 'Rivadavia 101',
        registroConabip: 544,
    },
    {
        nombre: 'Biblioteca Popular D. F. Sarmiento',
        localidad: 'Huinca Renanco',
        direccion: 'San Martín 305',
        registroConabip: 545,
    },
    {
        nombre: 'Juan Bautista Alberdi',
        localidad: 'Laboulaye',
        direccion: 'España 7',
        registroConabip: 549,
    },
    {
        nombre: 'Biblioteca Popular Mariano Moreno',
        localidad: 'Río Cuarto',
        direccion: 'Sobremonte 1079',
        registroConabip: 555,
    },
    {
        nombre: 'Centro cultural y Biblioteca Popular San Francisco',
        localidad: 'San Francisco',
        direccion: 'Libertador Norte 159',
        registroConabip: 560,
    },
    {
        nombre: 'Biblioteca Popular Bernardino Rivadavia',
        localidad: 'Villa María',
        direccion: 'Tucumán 829',
        registroConabip: 567,
    },
    {
        nombre: 'Biblioteca Popular Sarmiento',
        localidad: 'Las Varillas',
        direccion: 'Bv.Sarmiento 170',
        registroConabip: 581,
    },
    {
        nombre: 'BIBLIOTECA POPULAR BARTOLOME MITRE',
        localidad: 'Monte Maíz',
        direccion: 'Jujuy 1476',
        registroConabip: 586,
    },
    {
        nombre: 'Biblioteca Popular Domingo Sarmiento',
        localidad: 'Río Cuarto',
        direccion: 'Belisario Roldán 201',
        registroConabip: 588,
    },
    {
        nombre: 'ASOCIACIÓN BIBLIOTECA POPULAR ALBERDI',
        localidad: 'Córdoba',
        direccion: '9 de Julio 2701',
        registroConabip: 870,
    },
    {
        nombre: 'JUSTO JOSE DE URQUIZA',
        localidad: 'Río Tercero',
        direccion: 'Alberdi 75',
        registroConabip: 873,
    },
    {
        nombre: 'Biblioteca Popular Nicolas Avellaneda',
        localidad: 'Cosquín',
        direccion: 'Gerónico 848',
        registroConabip: 1071,
    },
    {
        nombre: 'Biblioteca Popular Cultura y Progreso',
        localidad: 'Morteros',
        direccion: 'Mariano Moreno 16',
        registroConabip: 1176,
    },
    {
        nombre: 'Mariano Moreno',
        localidad: 'Dean Funes',
        direccion: 'Italia 163',
        registroConabip: 1403,
    },
    {
        nombre: 'Club Atlético Cultural y Biblioteca Popular Recreativo',
        localidad: 'Laborde',
        direccion: 'Belgrano 330',
        registroConabip: 1419,
    },
    {
        nombre: 'Biblioteca Popular Nicolás Avellaneda',
        localidad: 'Alta Gracia',
        direccion: 'España 26',
        registroConabip: 1541,
    },
    {
        nombre: 'Biblioteca Popular D. F. Sarmiento',
        localidad: 'Alta Gracia',
        direccion: 'Prudencio Bustos 345',
        registroConabip: 1647,
    },
    {
        nombre: 'La Bicicleta',
        localidad: 'Colonia Caroya',
        direccion: 'Av. San Martin 2224',
        registroConabip: 1959,
    },
    {
        nombre: 'Biblioteca Popular Armando Tellería',
        localidad: 'Elena',
        direccion: 'Buteler 80',
        registroConabip: 1756,
    },
    {
        nombre: 'Biblioteca Popular Juan Benitz',
        localidad: 'Monte Buez',
        direccion: '9 de Julio 351',
        registroConabip: 1758,
    },
    {
        nombre: 'Biblioteca Popular José Ingenieros',
        localidad: 'Freyre',
        direccion: 'Iturraspe 692',
        registroConabip: 1824,
    },
    {
        nombre: 'Biblioteca Popular Sarmiento',
        localidad: 'La Falda',
        direccion: '25 de Mayo 433',
        registroConabip: 1867,
    },
    {
        nombre: 'Biblioteca Popular José Ingenieros',
        localidad: 'Dean Funes',
        direccion: 'Independencia y Tucumán',
        registroConabip: 1872,
    },
    {
        nombre: 'Biblioteca Popular Domingo F. Sarmiento',
        localidad: 'Altos de Chipión',
        direccion: 'Sarmiento 402',
        registroConabip: 2008,
    },
    {
        nombre: 'Biblioteca Popular Domingo F. Sarmiento',
        localidad: 'Jovita',
        direccion: 'Moreno 320',
        registroConabip: 2021,
    },
    {
        nombre: 'Mariano Moreno',
        localidad: 'La Calera',
        direccion: 'Velez Sarfield 556',
        registroConabip: 2045,
    },
    {
        nombre: 'Biblioteca Popular Juventud Unida',
        localidad: 'Oliva',
        direccion: 'Av. Olmos 350',
        registroConabip: 2081,
    },
    {
        nombre: 'Biblioteca Popular José Mármol',
        localidad: 'Valle Hermoso',
        direccion: '25 de Mayo y Pueyrredón',
        registroConabip: 2148,
    },
    {
        nombre: 'Biblioteca Popular Domingo F. Sarmiento',
        localidad: 'Río Ceballos',
        direccion: 'San Martín 5273',
        registroConabip: 2157,
    },
    {
        nombre: 'Biblioteca Popular Domingo F. Sarmiento',
        localidad: 'Ticino',
        direccion: 'Intendente Lorenzati 348',
        registroConabip: 2162,
    },
    {
        nombre: 'Centro Social Cultural y Biblioteca Popular Pedro Sauberán',
        localidad: 'Los Surgentes',
        direccion: 'Carlos Sauberán 313',
        registroConabip: 2197,
    },
    {
        nombre: 'Asociación Cultural El Retoño y Biblioteca Popular Manuel Belgrano',
        localidad: 'Wenceslao Escalante',
        direccion: 'Italia y Salta',
        registroConabip: 2203,
    },
    {
        nombre: 'Biblioteca Popular Luis Jose de Tejeda',
        localidad: 'Córdoba',
        direccion: 'Ricardo Rojas 4331',
        registroConabip: 2257,
    },
    {
        nombre: 'Biblioteca Popular José María Paz',
        localidad: 'Sacanta',
        direccion: 'Belgrano 555',
        registroConabip: 2265,
    },
    {
        nombre: "Biblioteca Pública Municipal y Popular Dr. Ermes Desio",
        localidad: 'Corral de Bustos',
        direccion: 'Córdoba 664 - Sec. Cult',
        registroConabip: 2321,
    },
    {
        nombre: 'Biblioteca Popular Mariano Moreno',
        localidad: 'Capilla del Monte',
        direccion: 'Sarmiento y Rivadavia',
        registroConabip: 2330,
    },
    {
        nombre: 'Biblioteca Popular Infantil Almafuerte',
        localidad: 'Las Varillas',
        direccion: 'Dean Funes 600',
        registroConabip: 2360,
    },
    {
        nombre: 'Biblioteca Popular Municipal Mariano Moreno',
        localidad: 'Villa María',
        direccion: 'Sabattini 40',
        registroConabip: 2406,
    },
    {
        nombre: 'Biblioteca Popular Mariano Moreno',
        localidad: 'Guatimozin',
        direccion: 'Santa Fe 263',
        registroConabip: 2424,
    },
    {
        nombre: 'Biblioteca Popular Manuel Lainez',
        localidad: 'San Francisco',
        direccion: 'Almafuerte 1107',
        registroConabip: 2426,
    },
    {
        nombre: 'Biblioteca Popular y Centro Cultural Gral. San Martín',
        localidad: 'Oncativo',
        direccion: 'Rivadavia 549',
        registroConabip: 2534,
    },
    {
        nombre: 'BIBLIOTECA POPULAR JERÓNIMO LUIS DE CABRERA',
        localidad: 'General Cabrera',
        direccion: 'Las Heras 859',
        registroConabip: 2615,
    },
    {
        nombre: 'Biblioteca Popular Juan Bautista Alberdi,Comisión del Malambo y Amigos del Arte',
        localidad: 'Laborde',
        direccion: 'Dr. Senestrari 120',
        registroConabip: 2737,
    },
    {
        nombre: 'Biblioteca Popular Técnica - ENET Nº 1 Ambrosio Olmos',
        localidad: 'Río Cuarto',
        direccion: 'Baigorria 527',
        registroConabip: 2751,
    },
    {
        nombre: 'Biblioteca Popular Almafuerte',
        localidad: 'Santa Rosa de Calamuchita',
        direccion: 'Córdoba 550',
        registroConabip: 2768,
    },
    {
        nombre: 'Biblioteca popular y centro de ajedrez los amigos de la cultura',
        localidad: 'Córdoba',
        direccion: 'Pje. Mar Chiquita 4408',
        registroConabip: 2776,
    },
    // {
    //     nombre: 'AMIGOS DE LA BIBLIOTECA POPULAR SOCIAL Y CULTURAL BARTOLOME MITRE DE CALCHIN',
    //     localidad: 'Calchin',
    //     direccion: 'Santa Teresa 250',
    //     registroConabip: 2794,
    // },
    // {
    //     nombre: 'Biblioteca Popular Evaristo Segat',
    //     localidad: 'Río Cuarto',
    //     direccion: 'Alberdi 575',
    //     registroConabip: 2851,
    // },
    // {
    //     nombre: 'Biblioteca Popular San Martín',
    //     localidad: 'Marcos Juárez',
    //     direccion: 'Av. L.N. Alem 671',
    //     registroConabip: 2858,
    // },
    // {
    //     nombre: 'Biblioteca Popular Ricardo Rojas',
    //     localidad: 'Coronel Moldes',
    //     direccion: 'Avenida Rivadavia 150',
    //     registroConabip: 2866,
    // },
    // {
    //     nombre: 'Biblioteca Popular Teresita Lucchini',
    //     localidad: 'Arias',
    //     direccion: 'Av.San Martín 1065',
    //     registroConabip: 2884,
    // },
    // {
    //     nombre: 'Biblioteca Popular José Hernández',
    //     localidad: 'Coronel Baigorria',
    //     direccion: 'Mitre y Balgrano',
    //     registroConabip: 2900,
    // },
    // {
    //     nombre: 'Biblioteca Popular Tere Andruetto',
    //     localidad: 'Unquillo',
    //     direccion: 'Spilimbergo S/N',
    //     registroConabip: 2924,
    // },
    // {
    //     nombre: 'Biblioteca Popular José H. Porto',
    //     localidad: 'Carlos Paz',
    //     direccion: 'José H. Porto 96',
    //     registroConabip: 2978,
    // },
    // {
    //     nombre: 'Biblioteca Popular La Asunción de María',
    //     localidad: 'Elena',
    //     direccion: 'Pje. Cura Brochero 189',
    //     registroConabip: 3011,
    // },
    // {
    //     nombre: 'Biblioteca Popular de los Sagrados Corazones',
    //     localidad: 'Río Cuarto',
    //     direccion: 'Lamadrid 1660',
    //     registroConabip: 3015,
    // },
    // {
    //     nombre: 'Biblioteca Popular Dr. Raúl Scalabrini Ortiz ',
    //     localidad: 'Pasco',
    //     direccion: 'Belgrano 645',
    //     registroConabip: 3031,
    // },
    // {
    //     nombre: 'biblioteca popular y centro juvenil Malvinas Argentinas',
    //     localidad: 'Córdoba',
    //     direccion: 'B.Houssay 2080',
    //     registroConabip: 3042,
    // },
    // {
    //     nombre: 'Rosa Areal de Molina',
    //     localidad: 'Tanti',
    //     direccion: 'Salta 202',
    //     registroConabip: 3055,
    // },
    // {
    //     nombre: 'Biblioteca Popular Teniente Benjamín Matienzo',
    //     localidad: 'Córdoba',
    //     direccion: 'Fleming 2413 esq. Lagunilla',
    //     registroConabip: 3127,
    // },
    // {
    //     nombre: 'Biblioteca Popular Pbro. Guillermo Avila Vasquez',
    //     localidad: 'Río Primero',
    //     direccion: 'Pablo Robert 90',
    //     registroConabip: 3138,
    // },
    // {
    //     nombre: 'Club Atlético Biblioteca y Mutual Argentino',
    //     localidad: 'Marcos Juárez',
    //     direccion: 'Belgrano y Champagnat',
    //     registroConabip: 3139,
    // },
    // {
    //     nombre: 'Biblioteca Popular de Bella Vista y Fundación Padre Milesi',
    //     localidad: 'Córdoba',
    //     direccion: 'Rufino Zado 633',
    //     registroConabip: 3218,
    // },
    // {
    //     nombre: 'Biblioteca Popular 23 de Setiembre',
    //     localidad: 'James Craik',
    //     direccion: 'Bv. San Martín y Estados Unidos',
    //     registroConabip: 3520,
    // },
    // {
    //     nombre: 'Biblioteca Popular Efra',
    //     localidad: 'Berrotarán',
    //     direccion: 'Nicolás Berrotarán 151',
    //     registroConabip: 3568,
    // },
    // {
    //     nombre: 'Biblioteca Popular Hugo Wast',
    //     localidad: 'Córdoba',
    //     direccion: 'Carlos III 1713',
    //     registroConabip: 3572,
    // },
    // {
    //     nombre: 'Biblioteca Jorge Luis Borges',
    //     localidad: 'Las Varas',
    //     direccion: 'América 274',
    //     registroConabip: 3576,
    // },
    // {
    //     nombre: 'Biblioteca Popular Luis Alberto Guerberoff',
    //     localidad: 'Pozo del Molle',
    //     direccion: 'Rivadavia 177',
    //     registroConabip: 3586,
    // },
    // {
    //     nombre: 'Lidia Cesanelli',
    //     localidad: 'Marcos Juárez',
    //     direccion: 'San Juan 1090',
    //     registroConabip: 3592,
    // },
    // {
    //     nombre: 'Biblioteca Popular Isla Verde',
    //     localidad: 'Isla Verde',
    //     direccion: '25 de Mayo 275',
    //     registroConabip: 3593,
    // },
    // {
    //     nombre: 'Biblioteca Popular Secundario Carnerillo',
    //     localidad: 'Carnerillo',
    //     direccion: 'Martín Gil 134',
    //     registroConabip: 3595,
    // },
    // {
    //     nombre: 'Biblioteca Popular Martín Fierro',
    //     localidad: 'Las Perdices',
    //     direccion: 'Sarmiento 824',
    //     registroConabip: 3596,
    // },
    // {
    //     nombre: 'Biblioteca Popular Orden del Colmenar',
    //     localidad: 'Mina Clavero',
    //     direccion: 'San Martín 411',
    //     registroConabip: 3620,
    // },
    // {
    //     nombre: 'Biblioteca Popular Marcela Rodriguez',
    //     localidad: 'La Francia',
    //     direccion: 'Bv.Córdoba esq.P.Lencinas',
    //     registroConabip: 3623,
    // },
    // {
    //     nombre: 'Biblioteca Popular Leopoldo Lugones',
    //     localidad: 'Villa Giardino',
    //     direccion: 'Av. San Martín 361',
    //     registroConabip: 3629,
    // },
    // {
    //     nombre: 'Biblioteca Popular Ricardo Rojas',
    //     localidad: 'Villa Rumipal',
    //     direccion: 'Velez Sarfield 498',
    //     registroConabip: 3645,
    // },
    // {
    //     nombre: 'Biblioteca Popular Luis Roberto Altamira',
    //     localidad: 'Villa Nueva',
    //     direccion: 'Dean Funes 1259',
    //     registroConabip: 3691,
    // },
    // {
    //     nombre: 'Biblioteca Popular Profesor Américo Pablo Tissera',
    //     localidad: 'Carrilobo',
    //     direccion: 'Semana Santa s/n',
    //     registroConabip: 3702,
    // },
    // {
    //     nombre: 'República Argentina',
    //     localidad: 'Córdoba',
    //     direccion: 'Agua de Oro 3278',
    //     registroConabip: 3707,
    // },
    // {
    //     nombre: 'Biblioteca Popular José Hernández',
    //     localidad: 'La Playosa',
    //     direccion: 'Bv. Córdoba 775',
    //     registroConabip: 3723,
    // },
    // {
    //     nombre: 'Biblioteca Popular Alfonsina Storni',
    //     localidad: 'Sampacho',
    //     direccion: 'Belgrano 690',
    //     registroConabip: 3729,
    // },
    // {
    //     nombre: 'Biblioteca Popular Mun. Quilcahuasi',
    //     localidad: 'Tránsito',
    //     direccion: 'República Argentina 50',
    //     registroConabip: 3748,
    // },
    // {
    //     nombre: 'Biblioteca Popular Dr. Manuel Belgrano',
    //     localidad: 'Villa General Belgrano',
    //     direccion: 'Julio A.Roca 128',
    //     registroConabip: 3679,
    // },
    // {
    //     nombre: 'Biblioteca Popular Nuestra Señora de Luján',
    //     localidad: 'Villa Huidobro',
    //     direccion: 'Av.M.Espinosa 26 / 40',
    //     registroConabip: 3772,
    // },
    // {
    //     nombre: 'Biblioteca Popular Alfonsina Storni',
    //     localidad: 'Córdoba',
    //     direccion: 'Muluches E/ Boro y Cruz Alta',
    //     registroConabip: 3845,
    // },
    // {
    //     nombre: 'Biblioteca Pública y Popular Colonia Vignaud',
    //     localidad: 'Colonia Vignaud',
    //     direccion: 'BELGRANO S/N',
    //     registroConabip: 3853,
    // },
    // {
    //     nombre: 'Biblioteca Popular Babel',
    //     localidad: 'La Falda',
    //     direccion: 'Avda. España (Ex Estación Ferrocarril)',
    //     registroConabip: 3867,
    // },
    // {
    //     nombre: 'BIBLIOTECA POPULAR RVDO.FELIX ENRIQUE',
    //     localidad: 'La Cruz',
    //     direccion: 'San Martín 301',
    //     registroConabip: 3904,
    // },
    // {
    //     nombre: 'Biblioteca Popular Mi Jardín',
    //     localidad: 'Córdoba',
    //     direccion: 'Cabo Segundo Gonzalez 2153',
    //     registroConabip: 3905,
    // },
    // {
    //     nombre: 'Biblioteca Popular Esc. D.F.Sarmiento',
    //     localidad: 'Cavanagh',
    //     direccion: 'Almirante Brown 454',
    //     registroConabip: 3915,
    // },
    // {
    //     nombre: 'Biblioteca Popular Asociación Creciendo',
    //     localidad: 'La Paquita',
    //     direccion: '20 de Junio 398',
    //     registroConabip: 3931,
    // },
    // {
    //     nombre: 'Biblioteca Popular Juan Filloy',
    //     localidad: 'Melo',
    //     direccion: 'Santa Ana y España',
    //     registroConabip: 3958,
    // },
    // {
    //     nombre: 'biblioteca popular Los Hornillos',
    //     localidad: 'Los Hornillos',
    //     direccion: 'Bonnier S/N',
    //     registroConabip: 3983,
    // },
    // {
    //     nombre: 'Biblioteca Popular Martín Fierro',
    //     localidad: 'Balnearia',
    //     direccion: 'Ex-Estación FCGB',
    //     registroConabip: 3990,
    // },
    // {
    //     nombre: 'BIBLIOTECA POPULAR MARIANO MORENO',
    //     localidad: 'San Francisco',
    //     direccion: 'Florencio Sánchez 667',
    //     registroConabip: 3997,
    // },
    // {
    //     nombre: 'Biblioteca Popular Teresa B. de Lancestremere',
    //     localidad: 'Camilo Aldao',
    //     direccion: 'Leandro N. Alem 1195',
    //     registroConabip: 4014,
    // },
    // {
    //     nombre:'Biblioteca Popular San José',
    //     localidad: 'Malagueño',
    //     direccion: 'Puerto Argentino 370',
    //     registroConabip: 4026,
    // },
    // {
    //     nombre: 'Biblioteca Popular Atahualpa',
    //     localidad: 'Córdoba',
    //     direccion: 'Tomas de Irovi 401',
    //     registroConabip: 4028,
    // },
    // {
    //     nombre: 'Biblioteca Popular Del Campillo',
    //     localidad: 'Del Campillo',
    //     direccion: 'San Martín 417',
    //     registroConabip: 4037,
    // },
    // {
    //     nombre: 'Biblioteca Popular y Centro Cultural Rayuela',
    //     localidad: 'Santiago Temple',
    //     direccion: 'Mariano Moreno 851',
    //     registroConabip: 4042,
    // },
    // {
    //     nombre: 'Asociación Vecinal Alto privado Norte y Biblioteca Popular Santiago Coronel ',
    //     localidad: 'Río Cuarto',
    //     direccion: 'Obispo Buteler (Complejo del Abasto L-24) 1289',
    //     registroConabip: 4097,
    // },
    // {
    //     nombre: 'Biblioteca Popular Flavio Arnal Ponti',
    //     localidad: 'Anisacate',
    //     direccion: 'Los Chañaritos',
    //     registroConabip: 4101,
    // },
    // {
    //     nombre: 'Biblioteca Popular Manuela R. Medina',
    //     localidad: 'Las Peñas Sud',
    //     direccion: 'Avda. 22 de octubre s/n y 9 de Julio',
    //     registroConabip: 4126,
    // },
    // {
    //     nombre: 'Biblioteca José Hernández',
    //     localidad: 'Alicia',
    //     direccion: 'Bv Las Malvinas 616',
    //     registroConabip: 4145,
    // },
    // {
    //     nombre: 'Biblioteca Popular Cdr. Enrique Carlos Aragón King',
    //     localidad: 'Río Ceballos',
    //     direccion: 'Avda. San Martín 8759',
    //     registroConabip: 4203,
    // },
    // {
    //     nombre: 'Biblioteca Popular Villa de las Rosas',
    //     localidad: 'Villa de las Rosas',
    //     direccion: '25 de Mayo 334',
    //     registroConabip: 4213,
    // },
    // {
    //     nombre: 'Biblioteca Popular Morrison',
    //     localidad: 'Morrison',
    //     direccion: 'Cristo Rey 81',
    //     registroConabip: 4218,
    // },
    // {
    //     nombre: 'Biblioteca Popular Porteña',
    //     localidad: 'Porteña',
    //     direccion: 'Mitre 481',
    //     registroConabip: 4232,
    // },
    // {
    //     nombre: 'Biblioteca Popular Julio Cortázar',
    //     localidad: 'Córdoba',
    //     direccion: 'Arroyo Diego de Torres 1332',
    //     registroConabip: 4243,
    // },
    // {
    //     nombre: 'Biblioteca Popular Alejo Carmen Guzmán',
    //     localidad: 'Villa Santa Rosa',
    //     direccion: 'San Martín 887',
    //     registroConabip: 4244,
    // },
    // {
    //     nombre: 'Biblioteca Popular María Salemen',
    //     localidad: 'Córdoba',
    //     direccion: 'Velez Sarsfield 137',
    //     registroConabip: 4245,
    // },
    // {
    //     nombre: 'Biblioteca Popular Cawana',
    //     localidad: 'Unquillo',
    //     direccion: 'El Hornero s/n esquina Av 5 de Octubre, Av. Cabana',
    //     registroConabip: 4277,
    // },
    // {
    //     nombre: 'Biblioteca Popular Libertad por la Integración Latinoamericana',
    //     localidad: 'Córdoba',
    //     direccion: 'Avda. Alem 1702',
    //     registroConabip: 4286,
    // },
    // {
    //     nombre: 'Biblioteca Popular y Centro Cultural Dumesnil',
    //     localidad: 'La Calera',
    //     direccion: 'Ruta Pcial. E 64 939',
    //     registroConabip: 4290,
    // },
    // {
    //     nombre: 'Biblioteca Popular de Luyaba',
    //     localidad: 'Luyaba',
    //     direccion: 'Ruta Provincial 14 s/n',
    //     registroConabip: 4294,
    // },
    // {
    //     nombre: 'Biblioteca Popular Jorge Luis Borges- La Puerta',
    //     localidad: 'La Puerta',
    //     direccion: 'Bv Belgrano y 9 de Julio',
    //     registroConabip: 4312,
    // },
    // {
    //     nombre: 'Biblioteca Popular del Bicentenario',
    //     localidad: 'Córdoba',
    //     direccion: 'Calle 6 s/n',
    //     registroConabip: 4322,
    // },
    // {
    //     nombre: 'Biblioteca Popular José Marcial Enrique Vaudagna',
    //     localidad: 'La Tordilla',
    //     direccion: 'Avda. Libertador 761',
    //     registroConabip: 4343,
    // },
    // {
    //     nombre: 'Biblioteca Popular de Embalse Teresa Sul',
    //     localidad: 'Embalse',
    //     direccion: 'Hipólito Irigoyen 402',
    //     registroConabip: 4347,
    // },
    // {
    //     nombre: 'Biblioteca Popular La Urdimbre',
    //     localidad: 'Villa Los Aromos',
    //     direccion: 'Los Chañares 940',
    //     registroConabip: 4362,
    // },
    // {
    //     nombre: 'Biblioteca Popular Garabatos',
    //     localidad: 'Anisacate',
    //     direccion: 'Jacaranda s/n',
    //     registroConabip: 4392,
    // },
    // {
    //     nombre: 'Biblioteca Popular El Manantial',
    //     localidad: 'Villa Cura Brochero',
    //     direccion: 'Belgrano 768',
    //     registroConabip: 4395,
    // },
    // {
    //     nombre: 'Biblioteca Popular Ataliva Herrera',
    //     localidad: 'Estancia Vieja',
    //     direccion: 'Avenida San Martin 37',
    //     registroConabip: 4411,
    // },
    // {
    //     nombre: 'Biblioteca Popular Los Morteritos',
    //     localidad: 'Villa Santa Cruz del Lago',
    //     direccion: 'Las Verbenas S/N',
    //     registroConabip: 4422,
    // }
]